name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnowdb"
database_id = "7a236e91-2a9b-411f-a5ed-2bb9700b9df9"
